// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfECh7om7NgEt2qj1Ajs0vc6n6Tlk8sI',
    appId: '1:876118636125:web:773177eb8b43c02bc17fb4',
    messagingSenderId: '876118636125',
    projectId: 'ecom-22991',
    authDomain: 'ecom-22991.firebaseapp.com',
    storageBucket: 'ecom-22991.appspot.com',
    measurementId: 'G-J2411W2F78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLllU8Hgq62lG5YYFzuBIM6Cf0azcTek',
    appId: '1:876118636125:android:0a64cdb2eb795ac5c17fb4',
    messagingSenderId: '876118636125',
    projectId: 'ecom-22991',
    storageBucket: 'ecom-22991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCysj_giF2xlp779HkX_d1LBVOe5i7cQRc',
    appId: '1:876118636125:ios:5d6483a5dbb3b87ac17fb4',
    messagingSenderId: '876118636125',
    projectId: 'ecom-22991',
    storageBucket: 'ecom-22991.appspot.com',
    iosClientId: '876118636125-2n9hlunj81jpbg7u8s1jlsdcfmpvauvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCysj_giF2xlp779HkX_d1LBVOe5i7cQRc',
    appId: '1:876118636125:ios:5d6483a5dbb3b87ac17fb4',
    messagingSenderId: '876118636125',
    projectId: 'ecom-22991',
    storageBucket: 'ecom-22991.appspot.com',
    iosClientId: '876118636125-2n9hlunj81jpbg7u8s1jlsdcfmpvauvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
